let sb=null, user=null, teams=[], players=[], T=null, S="home", G={}, drills=[];
let timer={id:null,left:0,running:false}, int=null, audioCtx=null;

const $=id=>document.getElementById(id);
const team=()=>teams.find(t=>t.id===T);
const esc=x=>String(x??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const jersey=p=>`<span class="jersey">${esc(p.jersey_number)}</span>`;

function configured(){const url=String(window.SUPABASE_URL||"").trim();const key=String(window.SUPABASE_PUBLISHABLE_KEY||window.SUPABASE_ANON_KEY||"").trim();return !!url&&!!key&&!url.startsWith("PASTE-")&&!key.startsWith("PASTE-")}
function showFatal(message){$("app").innerHTML=`<div class="auth"><div class="card"><h1>Coach Assistant</h1><p class="sub">The app could not start.</p><div class="error">${esc(message)}</div><p class="sub">Check config.js and your Supabase project, then reload this page.</p></div></div>`}
function go(s){S=s;$("drawer").classList.add("hide");render()}
function auth(err=""){$("app").innerHTML=`<div class="auth"><div class="card"><h1>Coach Assistant</h1><p class="sub">Sign in to sync your coaching data across your iPhone and iPad.</p>${err?`<div class="error">${esc(err)}</div>`:""}<input id="email" type="email" autocomplete="email" placeholder="Email"><input id="pw" type="password" autocomplete="current-password" placeholder="Password"><div class="buttons"><button class="primary" onclick="signin()">SIGN IN</button><button class="secondary" onclick="signup()">CREATE ACCOUNT</button></div></div></div>`}
async function signin(){const email=$("email")?.value.trim(),password=$("pw")?.value||"";if(!email||!password)return auth("Enter your email and password.");const r=await sb.auth.signInWithPassword({email,password});if(r.error)auth(r.error.message)}
async function signup(){const email=$("email")?.value.trim(),password=$("pw")?.value||"";if(!email||!password)return auth("Enter an email and password.");if(password.length<6)return auth("Use a password of at least 6 characters.");const r=await sb.auth.signUp({email,password});if(r.error)return auth(r.error.message);auth("Account created. If Supabase asks you to confirm your email, do that first, then sign in.")}
async function boot(){if(!configured())return showFatal("Supabase is not configured. Open config.js and enter your Project URL and Publishable Key.");try{const key=String(window.SUPABASE_PUBLISHABLE_KEY||window.SUPABASE_ANON_KEY||"").trim();sb=window.supabase.createClient(String(window.SUPABASE_URL).trim(),key,{auth:{autoRefreshToken:true,persistSession:true,detectSessionInUrl:true}})}catch(e){return showFatal("Supabase could not be initialised: "+(e.message||e))}const r=await sb.auth.getSession();if(r.error)return showFatal(r.error.message);user=r.data.session?.user||null;if(user)await load();else auth();sb.auth.onAuthStateChange(async(_event,session)=>{user=session?.user||null;if(user)await load();else auth()})}
async function load(){try{let r=await sb.from("teams").select("*").order("created_at");if(r.error)throw r.error;teams=r.data||[];if(!teams.length){r=await sb.from("teams").insert([{user_id:user.id,name:"West Belconnen Team 1"},{user_id:user.id,name:"West Belconnen Team 2"}]).select();if(r.error)throw r.error;teams=r.data||[]}T=T&&teams.some(t=>t.id===T)?T:teams[0]?.id;await loadTeam();r=await sb.from("drills").select("*").order("created_at");if(r.error)throw r.error;drills=r.data||[];render()}catch(e){showFatal("Could not load your coaching data: "+(e.message||e))}}
async function loadTeam(){if(!T){players=[];G={};return}let r=await sb.from("players").select("*").eq("team_id",T).order("jersey_number");if(r.error)throw r.error;players=r.data||[];if(!players.length){r=await sb.from("players").insert([4,7,9,11,12].map((n,i)=>({team_id:T,name:"Player "+(i+1),jersey_number:n}))).select();if(r.error)throw r.error;players=r.data||[]}G={};players.forEach((p,i)=>G[p.id]={one:0,two:0,three:0,foul:0,off:0,on:i<5})}
async function sw(id){T=id;await loadTeam();render()}
function render(){$("team").textContent=(team()?.name||"TEAM").toUpperCase();({home,game,bench,history,practice,season,teams:teamsScreen,settings}[S]||home)()}
function home(){$("app").innerHTML=`<h1>Coach Assistant</h1><p class="sub">Cloud synced · no game clock</p><div class="card"><div class="buttons">${teams.map(t=>`<button class="secondary" onclick="sw('${t.id}')">${esc(t.name)}</button>`).join("")}</div></div><div class="grid" style="margin-top:10px"><button class="action" onclick="go('game')"><b>🏀 Game</b><span>Points and fouls</span></button><button class="action" onclick="go('bench')"><b>🔄 Bench</b><span>Substitutions</span></button><button class="action" onclick="go('history')"><b>📅 History</b><span>Completed games</span></button><button class="action" onclick="go('practice')"><b>⏱ Practice</b><span>Custom drills</span></button><button class="action" onclick="go('season')"><b>📊 Season</b><span>Cumulative totals</span></button><button class="action" onclick="go('teams')"><b>👕 Teams</b><span>Players</span></button></div>`}
function game(){let total=Object.values(G).reduce((a,g)=>a+g.one+2*g.two+3*g.three,0);$("app").innerHTML=`<h1>Game</h1><p class="sub">${esc(team()?.name||"")}</p><div class="card"><div class="scorebox"><div><div class="score">${total}</div><div class="sub">YOUR SCORE</div></div><div><input id="opp" placeholder="Who are we playing?"><input id="os" type="number" min="0" placeholder="Opposition final score"></div></div><div class="buttons"><button class="primary" onclick="go('bench')">OPEN BENCH</button><button class="success" onclick="endGame()">END / SAVE GAME</button><button class="danger" onclick="clearLive()">CLEAR</button></div></div><h2>Players</h2><div class="players">${players.map(pc).join("")}</div>`}
function pc(p){let g=G[p.id],pts=g.one+2*g.two+3*g.three,fo=g.foul===5;return `<div class="player${fo?" fouled-out":""}">${jersey(p)}<b>${esc(p.name)} #${esc(p.jersey_number)}</b><div class="stats">PTS ${pts} · FOUL ${g.foul}/5 · SUB OFF ${g.off}${fo?" · FOULED OUT":""}</div><div class="buttons"><button class="primary" onclick="pts('${p.id}',1)">+1</button><button class="primary" onclick="pts('${p.id}',2)">+2</button><button class="primary" onclick="pts('${p.id}',3)">+3</button><button class="foul" onclick="foul('${p.id}')">FOUL</button><button class="${g.on?"danger":"success"}" onclick="sub('${p.id}')">${g.on?"SUB OFF":"SUB ON"}</button></div></div>`}
function pts(id,n){G[id][n===1?"one":n===2?"two":"three"]++;render()}
function foul(id){if(G[id].foul<5){G[id].foul++;if(G[id].foul===5)G[id].on=false}render()}
function sub(id){let g=G[id];if(g.foul>=5)return alert("Player has fouled out and cannot return to the court.");if(g.on){g.on=false;g.off++}else if(Object.values(G).filter(x=>x.on).length<5)g.on=true;else return alert("Five players are already on court.");render()}
function clearLive(){if(confirm("Clear current live game?")){players.forEach((p,i)=>G[p.id]={one:0,two:0,three:0,foul:0,off:0,on:i<5});render()}}
async function endGame(){let opponent=$("opp")?.value.trim(),os=Number($("os")?.value);if(!opponent)return alert("Enter who you are playing.");if(!Number.isInteger(os)||os<0)return alert("Enter opposition final score.");let my=Object.values(G).reduce((a,g)=>a+g.one+2*g.two+3*g.three,0);let r=await sb.from("games").insert({team_id:T,opponent,team_score:my,opponent_score:os}).select().single();if(r.error)return alert(r.error.message);let rows=players.map(p=>{let g=G[p.id];return{game_id:r.data.id,player_id:p.id,points_1:g.one,points_2:g.two,points_3:g.three,fouls:g.foul,sub_off:g.off}});r=await sb.from("game_player_stats").insert(rows);if(r.error)return alert(r.error.message);alert(`Saved ${my}-${os} vs ${opponent}`);clearLive();go("history")}
function bench(){$("app").innerHTML=`<h1>Bench</h1><p class="sub">Quick substitution screen.</p><div class="benchcols"><div class="bench"><h3>ON COURT · ${players.filter(p=>G[p.id].on).length}/5</h3>${players.filter(p=>G[p.id].on).map(bi).join("")}</div><div class="bench"><h3>BENCH · ${players.filter(p=>!G[p.id].on).length}</h3>${players.filter(p=>!G[p.id].on).map(bi).join("")}</div></div>`}
function bi(p){let g=G[p.id],fo=g.foul===5;return `<div class="benchitem${fo?" fouled-out":""}">${jersey(p)}<b>${esc(p.name)}<br><small>${g.foul}/5 fouls · ${g.off} sub offs${fo?" · FOULED OUT":""}</small></b><button class="${g.on?"danger":"success"}" onclick="sub('${p.id}')">${g.on?"SUB OFF":"SUB ON"}</button></div>`}
async function history(){let r=await sb.from("games").select("*").eq("team_id",T).order("game_date",{ascending:false}).order("created_at",{ascending:false});if(r.error)return showFatal(r.error.message);let gs=r.data||[];$("app").innerHTML=`<h1>Game History</h1><p class="sub">${esc(team()?.name||"")}</p><div class="list">${gs.map(g=>{let x=g.team_score>g.opponent_score?"WIN":g.team_score<g.opponent_score?"LOSS":"DRAW";return `<div class="row"><b>${g.game_date}<br>vs ${esc(g.opponent)}<br><span class="badge ${x==="LOSS"?"loss":""}">${x}</span></b><strong>${g.team_score} - ${g.opponent_score}</strong><button class="secondary" onclick="viewGame('${g.id}')">VIEW</button></div>`}).join("")||"<div class=\"card\">No games saved.</div>"}</div>`}
async function viewGame(id){let a=await sb.from("games").select("*").eq("id",id).single();if(a.error)return alert(a.error.message);let b=await sb.from("game_player_stats").select("*,players(name,jersey_number)").eq("game_id",id);if(b.error)return alert(b.error.message);let g=a.data,r=b.data||[];$("app").innerHTML=`<h1>vs ${esc(g.opponent)}</h1><p class="sub">${g.game_date}</p><div class="card"><div class="scorebox"><div class="score">${g.team_score}</div><div class="score">${g.opponent_score}</div></div><button class="secondary" onclick="go('history')">BACK</button></div><h2>Player Stats</h2><div class="card" style="overflow:auto"><table><tr><th>Player</th><th>PTS</th><th>1</th><th>2</th><th>3</th><th>FOUL</th><th>SUB OFF</th></tr>${r.map(x=>`<tr><td>#${x.players.jersey_number} ${esc(x.players.name)}</td><td>${x.points_1+2*x.points_2+3*x.points_3}</td><td>${x.points_1}</td><td>${x.points_2}</td><td>${x.points_3}</td><td>${x.fouls}/5</td><td>${x.sub_off}</td></tr>`).join("")}</table></div>`}
function practice(){$("app").innerHTML=`<h1>Practice</h1><p class="sub">Cloud-saved custom drills.</p><div class="timer"><div>${esc(drills.find(x=>x.id===timer.id)?.name||"Select a drill")}</div><div class="time">${fmt(timer.left)}</div><div class="buttons" style="justify-content:center"><button class="success" onclick="start()">START</button><button class="secondary" onclick="pause()">PAUSE</button><button class="danger" onclick="resetTimer()">RESET</button></div></div><div class="card"><button class="primary" onclick="addDrill()">＋ ADD DRILL</button><div class="list" style="margin-top:8px">${drills.map(d=>`<div class="row"><b>${esc(d.name)}<small>${d.minutes} min</small></b><button class="secondary" onclick="sel('${d.id}')">SELECT</button><button class="danger" onclick="delDrill('${d.id}')">DELETE</button></div>`).join("")}</div></div>`}
function fmt(x){return String(Math.floor(x/60)).padStart(2,"0")+":"+String(x%60).padStart(2,"0")}
function sel(id){timer.id=id;timer.left=(drills.find(x=>x.id===id)?.minutes||0)*60;render()}
function start(){if(!timer.id)return alert("Select a drill.");try{const AC=window.AudioContext||window.webkitAudioContext;if(AC){if(!audioCtx)audioCtx=new AC();if(audioCtx.state==="suspended")audioCtx.resume()}}catch(e){}clearInterval(int);timer.running=true;int=setInterval(()=>{timer.left--;if(timer.left===60||timer.left===0)beep();if(timer.left<=0){timer.left=0;timer.running=false;clearInterval(int)}render()},1000);render()}
function pause(){timer.running=false;clearInterval(int);render()}
function resetTimer(){pause();timer.left=timer.id?(drills.find(x=>x.id===timer.id)?.minutes||0)*60:0;render()}
function beep(){try{const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;if(!audioCtx)audioCtx=new AC();if(audioCtx.state==="suspended")audioCtx.resume();let o=audioCtx.createOscillator(),g=audioCtx.createGain();o.frequency.value=1800;g.gain.value=.08;o.connect(g);g.connect(audioCtx.destination);o.start();setTimeout(()=>{try{o.stop()}catch(e){}},180)}catch(e){}}
async function addDrill(){const name=prompt("Drill name");if(!name)return;const minutes=Number(prompt("Minutes"));if(!Number.isFinite(minutes)||minutes<=0)return;const r=await sb.from("drills").insert({team_id:T,name,minutes}).select().single();if(r.error)return alert(r.error.message);drills.push(r.data);render()}
async function delDrill(id){if(!confirm("Delete this drill?"))return;const r=await sb.from("drills").delete().eq("id",id);if(r.error)return alert(r.error.message);drills=drills.filter(d=>d.id!==id);if(timer.id===id){timer.id=null;timer.left=0}render()}
function teamsScreen(){$("app").innerHTML=`<h1>Teams & Players</h1><p class="sub">Manage your teams and roster.</p><div class="buttons">${teams.map(t=>`<button class="secondary" onclick="sw('${t.id}')">${esc(t.name)}</button>`).join("")}<button class="primary" onclick="saveTeam()">ADD TEAM</button></div><h2>${esc(team()?.name||"")} — Players</h2><div class="list">${players.map(p=>`<div class="row"><b>#${esc(p.jersey_number)} ${esc(p.name)}</b><button class="secondary" onclick="editPlayer('${p.id}')">EDIT</button><button class="danger" onclick="removePlayer('${p.id}')">DELETE</button></div>`).join("")||"<div class=\"card\">No players.</div>"}</div><button class="primary full" style="margin-top:10px" onclick="addPlayer()">ADD PLAYER</button>`}
async function saveTeam(){const name=prompt("Team name");if(!name)return;const r=await sb.from("teams").insert({user_id:user.id,name:name.trim()}).select().single();if(r.error)return alert(r.error.message);teams.push(r.data);T=r.data.id;await loadTeam();render()}
async function addPlayer(){const name=prompt("Player name");if(!name)return;const jerseyNo=Number(prompt("Jersey number"));if(!Number.isInteger(jerseyNo))return alert("Enter a valid jersey number.");const r=await sb.from("players").insert({team_id:T,name:name.trim(),jersey_number:jerseyNo}).select().single();if(r.error)return alert(r.error.message);players.push(r.data);G[r.data.id]={one:0,two:0,three:0,foul:0,off:0,on:false};render()}
async function editPlayer(id){const p=players.find(x=>x.id===id);if(!p)return;const name=prompt("Player name",p.name);if(!name)return;const jerseyNo=Number(prompt("Jersey number",p.jersey_number));if(!Number.isInteger(jerseyNo))return alert("Enter a valid jersey number.");const r=await sb.from("players").update({name:name.trim(),jersey_number:jerseyNo}).eq("id",id);if(r.error)return alert(r.error.message);p.name=name.trim();p.jersey_number=jerseyNo;render()}
async function removePlayer(id){if(!confirm("Delete this player?"))return;const r=await sb.from("players").delete().eq("id",id);if(r.error)return alert(r.error.message);players=players.filter(p=>p.id!==id);delete G[id];render()}
async function season(){let r=await sb.from("game_player_stats").select("*,players(name,jersey_number),games!inner(team_id)").eq("games.team_id",T);if(r.error)return showFatal(r.error.message);let totals={};(r.data||[]).forEach(x=>{const p=x.players;if(!p)return;let id=x.player_id;if(!totals[id])totals[id]={name:p.name,jersey:p.jersey_number,games:0,pts:0,fouls:0,off:0};totals[id].games++;totals[id].pts+=(x.points_1||0)+2*(x.points_2||0)+3*(x.points_3||0);totals[id].fouls+=x.fouls||0;totals[id].off+=x.sub_off||0});$("app").innerHTML=`<h1>Season</h1><p class="sub">Cumulative player totals.</p><div class="card" style="overflow:auto"><table><tr><th>Player</th><th>GP</th><th>PTS</th><th>FOUL</th><th>SUB OFF</th></tr>${Object.values(totals).map(x=>`<tr><td>#${esc(x.jersey)} ${esc(x.name)}</td><td>${x.games}</td><td>${x.pts}</td><td>${x.fouls}</td><td>${x.off}</td></tr>`).join("")||"<tr><td colspan=5>No saved game stats yet.</td></tr>"}</table></div>`}
function settings(){$("app").innerHTML=`<h1>Settings</h1><p class="sub">Account and app settings.</p><div class="card"><p>Signed in as <b>${esc(user?.email||"")}</b></p><button class="danger full" onclick="sb.auth.signOut()">SIGN OUT</button></div>`}

document.querySelectorAll("[data-s]").forEach(b=>b.onclick=()=>go(b.dataset.s));
$("close").onclick=()=>$("drawer").classList.add("hide");
window.addEventListener("load",boot);